In [23]:
#Required packages for importing and transforming data
import requests
import os
import pandas as pd
from sqlalchemy import create_engine, text
import psycopg2

#Neon database URL secret
neon_url = os.environ["NEON_DATABASE_URL"]

#Creating engine to connect to database 
engine = create_engine(neon_url)

#Importing data from neon with SQL query
query = """
SELECT *
FROM polar_data
"""
neon_data = pd.read_sql(text(query), engine)

In [24]:
neon_data.head(1)

,id,upload_time,polar_user,device,device_id,start_time,start_time_utc_offset,duration,distance,heart_rate,...,has_route,detailed_sport_info,calories,running_index,fat_percentage,carbohydrate_percentage,protein_percentage,heart_rate_zones,samples,training_load_pro
0,5p76vJKB,2026-01-13T00:07:36Z,https://www.polaraccesslink.com/v3/users/47052005,Polar Grit X Pro,AB64EE2D,2026-01-13T07:17:14,780,PT2724.716S,8169.0,"{'average': 140, 'maximum': 149}",...,True,RUNNING,600,63.0,45,55,0,"[{'index': 0, 'lower_limit': 99, 'upper_limit'...","[{'recording_rate': 1, 'sample_type': 0, 'data...","{'cardio-load': 54.5021, 'cardio-load-interpre..."

In [25]:
test = neon_data

In [32]:
test['upload_time'] = pd.to_datetime(neon_data['upload_time']).dt.tz_convert('Pacific/Auckland')
test['start_time'] = pd.to_datetime(neon_data['start_time'])

In [33]:
test.head(1)

,id,upload_time,polar_user,device,device_id,start_time,start_time_utc_offset,duration,distance,heart_rate,...,has_route,detailed_sport_info,calories,running_index,fat_percentage,carbohydrate_percentage,protein_percentage,heart_rate_zones,samples,training_load_pro
0,5p76vJKB,2026-01-13 13:07:36+13:00,https://www.polaraccesslink.com/v3/users/47052005,Polar Grit X Pro,AB64EE2D,2026-01-13 07:17:14,780,PT2724.716S,8169.0,"{'average': 140, 'maximum': 149}",...,True,RUNNING,600,63.0,45,55,0,"[{'index': 0, 'lower_limit': 99, 'upper_limit'...","[{'recording_rate': 1, 'sample_type': 0, 'data...","{'cardio-load': 54.5021, 'cardio-load-interpre..."